// PWA runtime helpers — install prompt capture, iOS meta tags, dynamic
// theme-color. The service worker + manifest are generated by
// vite-plugin-pwa (see vite.config.ts).
import favIcon from "../../imports/FAV_IPPOO.png";
// Icône d'installation (écran d'accueil iOS / invite « Ajouter à l'écran »).
import installIcon from "../../imports/INSURANCE.png";

let installPromptEvent: any = null;
const listeners = new Set<(can: boolean) => void>();

// One-time cleanup: the older service worker shipped a NetworkFirst rule on
// `/functions/v1/` with a 5s timeout that intermittently surfaced as
// "Failed to fetch" on Edge Function cold starts. We unregister it once and
// purge the affected caches so users immediately recover. The flag in
// localStorage prevents looping the unregister on every load.
async function purgeBrokenSW() {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
  try {
    if (localStorage.getItem("ippoo:sw:purged:v1") === "1") return;
  } catch { /* private mode — proceed anyway */ }
  try {
    const regs = await navigator.serviceWorker.getRegistrations();
    await Promise.all(regs.map((r) => r.unregister().catch(() => false)));
    if ("caches" in window) {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((n) => /ippoo-(api|nav|supabase)/.test(n))
          .map((n) => caches.delete(n).catch(() => false)),
      );
    }
    try { localStorage.setItem("ippoo:sw:purged:v1", "1"); } catch { /* ignore */ }
  } catch (err) {
    console.warn("SW cleanup skipped:", err);
  }
}

let setup = false;
export function setupPWA() {
  if (setup || typeof window === "undefined") return;
  setup = true;
  void purgeBrokenSW();
  try {
    // iOS standalone meta tags + apple-touch-icon
    const metas: [string, string][] = [
      ["apple-mobile-web-app-capable", "yes"],
      ["apple-mobile-web-app-status-bar-style", "default"],
      ["apple-mobile-web-app-title", "IPPOO"],
      ["mobile-web-app-capable", "yes"],
      ["format-detection", "telephone=no"],
    ];
    for (const [name, content] of metas) {
      let m = document.querySelector(`meta[name="${name}"]`) as HTMLMetaElement | null;
      if (!m) {
        m = document.createElement("meta");
        m.name = name;
        document.head.appendChild(m);
      }
      m.content = content;
    }
    setThemeColor("#FFFFFF");

    let apple = document.querySelector('link[rel="apple-touch-icon"]') as HTMLLinkElement | null;
    if (!apple) {
      apple = document.createElement("link");
      apple.rel = "apple-touch-icon";
      document.head.appendChild(apple);
    }
    apple.href = installIcon;

    for (const rel of ["icon", "shortcut icon"]) {
      let link = document.querySelector(`link[rel="${rel}"]`) as HTMLLinkElement | null;
      if (!link) {
        link = document.createElement("link");
        link.rel = rel;
        document.head.appendChild(link);
      }
      link.type = "image/png";
      link.href = favIcon;
    }
  } catch (err) {
    console.error("PWA setup failed:", err);
  }
  window.addEventListener("beforeinstallprompt", (e: any) => {
    e.preventDefault();
    installPromptEvent = e;
    listeners.forEach((l) => l(true));
  });
  window.addEventListener("appinstalled", () => {
    installPromptEvent = null;
    listeners.forEach((l) => l(false));
  });
}

/** Update the address-bar / status-bar color dynamically per screen. */
export function setThemeColor(color: string) {
  if (typeof document === "undefined") return;
  let theme = document.querySelector('meta[name="theme-color"]') as HTMLMetaElement | null;
  if (!theme) {
    theme = document.createElement("meta");
    theme.name = "theme-color";
    document.head.appendChild(theme);
  }
  theme.content = color;
}

export function canInstallPWA() {
  return !!installPromptEvent;
}

export function onInstallAvailable(cb: (can: boolean) => void) {
  listeners.add(cb);
  return () => listeners.delete(cb);
}

export async function promptInstallPWA() {
  if (!installPromptEvent) return false;
  try {
    installPromptEvent.prompt();
    const { outcome } = await installPromptEvent.userChoice;
    installPromptEvent = null;
    listeners.forEach((l) => l(false));
    return outcome === "accepted";
  } catch (err) {
    console.error("PWA install prompt failed:", err);
    return false;
  }
}

/** True when the app is launched standalone (added to home screen). */
export function isStandalone() {
  if (typeof window === "undefined") return false;
  return (
    window.matchMedia?.("(display-mode: standalone)").matches ||
    (window.navigator as any).standalone === true
  );
}
